"""empty message

Revision ID: 7032c4b2a040
Revises: 
Create Date: 2023-12-18 02:35:50.107794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7032c4b2a040'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('resumo', sa.String(length=80), nullable=False),
    sa.Column('contato', sa.String(length=80), nullable=False),
    sa.Column('senha', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('ong',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(length=80), nullable=False),
    sa.Column('categoria', sa.String(length=80), nullable=False),
    sa.Column('cidade', sa.String(length=80), nullable=False),
    sa.Column('uf', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('voluntario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('acao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_ong', sa.Integer(), nullable=True),
    sa.Column('id_volut', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_ong'], ['ong.id'], ),
    sa.ForeignKeyConstraint(['id_volut'], ['voluntario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('atuacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acao', sa.Integer(), nullable=True),
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id_acao'], ['acao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_acao', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_acao'], ['acao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.drop_table('atuacao')
    op.drop_table('acao')
    op.drop_table('voluntario')
    op.drop_table('ong')
    op.drop_table('user')
    # ### end Alembic commands ###
